#pragma once

#include <hwdef.h>

#define HAL_BOARD_NAME "infineon"

#ifdef HAL_HAVE_PIXRACER_LED
#error "use AP_NOTIFY_GPIO_LED_RGB_ENABLED in place of HAL_HAVE_PIXRACER_LED (and rename your pins!)"
#endif

#define CONFIG_HAL_BOARD_SUBTYPE HAL_BOARD_SUBTYPE_NONE

#ifndef HAL_PROGRAM_SIZE_LIMIT_KB
#define HAL_PROGRAM_SIZE_LIMIT_KB 4096
#endif  // HAL_PROGRAM_SIZE_LIMIT_KB

#define HAL_WITH_EKF_DOUBLE HAL_HAVE_HARDWARE_DOUBLE
#define HAL_HAVE_HARDWARE_DOUBLE 0

#define HAL_MEMORY_TOTAL_KB 256
#define HAL_MEM_CLASS HAL_MEMORY_TOTAL_KB

#define HAL_STORAGE_SIZE 16384

#define HAL_WITH_IO_MCU 0

#ifndef HAL_HAVE_BOARD_VOLTAGE
#define HAL_HAVE_BOARD_VOLTAGE 1
#endif

#ifndef HAL_HAVE_SERVO_VOLTAGE
#define HAL_HAVE_SERVO_VOLTAGE 0
#endif

#ifndef HAL_HAVE_SAFETY_SWITCH
#define HAL_HAVE_SAFETY_SWITCH 0
#endif
#define HAL_LOGGING_ENABLED 0

#define HAL_DISPLAY_ENABLED 0
#define AP_NOTIFY_TOSHIBALED_ENABLED 0
#define AP_NOTIFY_NCP5623_ENABLED 0
#define AP_NOTIFY_LP5562_ENABLED 0
#define AP_NOTIFY_IS31FL3195_ENABLED 0
#define AP_NOTIFY_PCA9685_ENABLED 0

//快速内存
#define __RAMFUNC__  CY_RAMFUNC_BEGIN
#define __FASTRAMFUNC__ CY_SECTION_ITCM_BEGIN

//关外设
#define OSD_ENABLED 0
#define OSD_PARAM_ENABLED 0
#define HAL_OSD_SIDEBAR_ENABLE 0
#define HAL_PLUSCODE_ENABLE 0

#define HAL_MSP_ENABLED 0
#define HAL_MSP_SENSORS_ENABLED 0
#define HAL_WITH_MSP_DISPLAYPORT 0
#define AP_MSP_INAV_FONTS_ENABLED 0

#define AP_VIDEOTX_ENABLED 0
#define AP_SMARTAUDIO_ENABLED 0
#define AP_TRAMP_ENABLED 0

#define AP_FRSKY_TELEM_ENABLED 0
#define AP_FRSKY_D_TELEM_ENABLED 0
#define AP_FRSKY_SPORT_TELEM_ENABLED 0
#define AP_FRSKY_SPORT_PASSTHROUGH_ENABLED 0
#define HAL_WITH_FRSKY_TELEM_BIDIRECTIONAL 0

#define AP_DDS_ENABLED 0
#define HAL_VISUALODOM_ENABLED 0
#define HAL_PROXIMITY_ENABLED 0
#define AP_RANGEFINDER_ENABLED 1
#define AP_OPTICALFLOW_ENABLED 1

#define AP_CAMERA_ENABLED 0
#define HAL_MOUNT_ENABLED 0
#define AP_GRIPPER_ENABLED 0
#define AP_WINCH_ENABLED 0
#define AP_RELAY_ENABLED 0
#define AP_SERVORELAYEVENTS_ENABLED 0
#define HAL_PARACHUTE_ENABLED 0
#define HAL_SPRAYER_ENABLED 0
#define HAL_RALLY_ENABLED 0

#define HAL_EFI_ENABLED 0
#define AP_ICENGINE_ENABLED 0
#define HAL_GENERATOR_ENABLED 0


//关没用传感器
#define AP_BARO_BMP085_ENABLED 0
#define AP_BARO_BMP280_ENABLED 0
#define AP_BARO_BMP388_ENABLED 0
#define AP_BARO_BMP581_ENABLED 0
#define AP_BARO_DPS280_ENABLED 0
#define AP_BARO_FBM320_ENABLED 0
#define AP_BARO_KELLERLD_ENABLED 0
#define AP_BARO_LPS2XH_ENABLED 0
#define AP_BARO_MS5607_ENABLED 0
#define AP_BARO_MS5611_ENABLED 0
#define AP_BARO_MS5637_ENABLED 0
#define AP_BARO_MS5837_ENABLED 0

#define AP_COMPASS_AK09916_ENABLED 0
#define AP_COMPASS_AK8963_ENABLED 0
#define AP_COMPASS_BMM150_ENABLED 0
#define AP_COMPASS_BMM350_ENABLED 0
#define AP_COMPASS_HMC5843_ENABLED 0
#define AP_COMPASS_ICM20948_ENABLED 0
#define AP_COMPASS_IST8308_ENABLED 0
#define AP_COMPASS_IST8310_ENABLED 0
#define AP_COMPASS_LIS2MDL_ENABLED 0
#define AP_COMPASS_LIS3MDL_ENABLED 0
#define AP_COMPASS_LSM303D_ENABLED 0
#define AP_COMPASS_LSM9DS1_ENABLED 0
#define AP_COMPASS_MAG3110_ENABLED 0
#define AP_COMPASS_MMC3416_ENABLED 0
#define AP_COMPASS_MMC5XX3_ENABLED 0
#define AP_COMPASS_QMC5883L_ENABLED 0
#define AP_COMPASS_RM3100_ENABLED 0

#define AP_AIRSPEED_ENABLED 0
#define AP_AIRSPEED_BACKEND_DEFAULT_ENABLED 0

// 如果有 GPS，建议只保留实际协议，比如 UBLOX
#define AP_GPS_ERB_ENABLED 0
#define AP_GPS_GSOF_ENABLED 0
#define AP_GPS_MAV_ENABLED 0
#define AP_GPS_NMEA_ENABLED 0
#define AP_GPS_NMEA_UNICORE_ENABLED 0
#define AP_GPS_NOVA_ENABLED 0
#define AP_GPS_SBF_ENABLED 0
#define AP_GPS_SBP_ENABLED 0
#define AP_GPS_SBP2_ENABLED 0
#define AP_GPS_SIRF_ENABLED 0
// 常见 GPS 保留 AP_GPS_UBLOX_ENABLED 1

// 电池只用模拟电压/电流时可关这些
#define AP_BATTERY_SMBUS_ENABLED 0
#define AP_BATTERY_FUELFLOW_ENABLED 0
#define AP_BATTERY_FUELLEVEL_PWM_ENABLED 0
#define AP_BATTERY_FUELLEVEL_ANALOG_ENABLED 0
#define AP_BATTERY_INA2XX_ENABLED 0
#define AP_BATTERY_SYNTHETIC_CURRENT_ENABLED 0
#define AP_BATTERY_SUM_ENABLED 0


#ifdef __cplusplus
// allow for static semaphores
#include <AP_HAL_Infineon/Semaphores.h>
#define HAL_Semaphore Infineon::Semaphore
#define HAL_BinarySemaphore Infineon::BinarySemaphore
#endif

#define AP_SCRIPTING_ENABLED 0

#define AP_MAVLINK_FTP_ENABLED 0

#define HAL_BOARD_TERRAIN_DIRECTORY "/APM/TERRAIN"

//HWDEF Default

#ifndef SCB0_DEFINITION
#define SCB0_DEFINITION 
#endif
#ifndef SCB1_DEFINITION
#define SCB1_DEFINITION 
#endif
#ifndef SCB2_DEFINITION
#define SCB2_DEFINITION 
#endif
#ifndef SCB3_DEFINITION
#define SCB3_DEFINITION 
#endif
#ifndef SCB4_DEFINITION
#define SCB4_DEFINITION 
#endif
#ifndef SCB5_DEFINITION
#define SCB5_DEFINITION 
#endif
#ifndef SCB6_DEFINITION
#define SCB6_DEFINITION 
#endif
#ifndef SCB7_DEFINITION
#define SCB7_DEFINITION 
#endif
#ifndef SCB8_DEFINITION
#define SCB8_DEFINITION 
#endif
#ifndef SCB9_DEFINITION
#define SCB9_DEFINITION 
#endif

#ifndef HAL_SERIAL_0
#define HAL_SERIAL_0 nullptr
#endif
#ifndef HAL_SERIAL_1
#define HAL_SERIAL_1 nullptr
#endif
#ifndef HAL_SERIAL_2
#define HAL_SERIAL_2 nullptr
#endif
#ifndef HAL_SERIAL_3
#define HAL_SERIAL_3 nullptr
#endif
#ifndef HAL_SERIAL_4
#define HAL_SERIAL_4 nullptr
#endif
#ifndef HAL_SERIAL_5
#define HAL_SERIAL_5 nullptr
#endif
#ifndef HAL_SERIAL_6
#define HAL_SERIAL_6 nullptr
#endif
#ifndef HAL_SERIAL_7
#define HAL_SERIAL_7 nullptr
#endif
#ifndef HAL_SERIAL_8
#define HAL_SERIAL_8 nullptr
#endif
#ifndef HAL_SERIAL_9
#define HAL_SERIAL_9 nullptr
#endif
#ifndef HAL_SERIAL_USB
#define HAL_SERIAL_USB nullptr
#endif

#ifndef I2C_DIFINITION
#define I2C_DIFINITION
#endif
#ifndef I2C_BUS_DEFINITION
#define I2C_BUS_DEFINITION
#endif

#ifndef SPI_DIFINITION
#define SPI_DIFINITION
#endif
#ifndef SPI_BUS_DEFINITION
#define SPI_BUS_DEFINITION
#endif
